### ISSUE TITLE
integrate some shell framework in container

### ISSUE THREAD

**Issue by ivoba** [nerdpress-org/docker-sf3#26]
would it be easy and useful to integrate oh-my-zsh or bash-it in the php container and autoenable relevant plugins, like symfony, composer, docker-compose?

this would provide a uniform, best practice shell style and legion features...

**Comment by gherkins** [comment]
yeah, i already tried that with oh-my-zsh.. 
but i failed to change the default shell for www-data. not shure why...

**Comment by gherkins** [comment]
zsh might be a bit hard to configure...
https://github.com/gherkins/docker-sf3/tree/feature-oh-my-zsh

@ivoba would you maybe add bash-it?

**Comment by ivoba** [comment]
i just checked bash-it again and unfortunatly it does not have the plugins or aliases that we would need like symfony or composer.
all other available plugins are rather not useful in the container.

i would propose we add a decent bash theme and copy/migrate the symfony&composer plugins from oh-my-zsh for bash, somehow

**Comment by gherkins** [comment]
hm, shouldn't be that hard...
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/symfony2/symfony2.plugin.zsh
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/composer/composer.plugin.zsh

i'd suggest we also integrate https://github.com/nerdpress-org/docker-sf3/issues/30 for sf command completion...

**Comment by gherkins** [comment]
mission accomplished 

thanks @datadarius 🎊
