### ISSUE TITLE
use wait-for-it for db container

### ISSUE THREAD

**Issue by ivoba** [nerdpress-org/docker-sf3#38]
i once in a while get this error

`ERROR: for sf_web  Cannot start service sf_web: Cannot link to a non running container: /sf_db AS /sf_web/db`

we could probably fix this with usage of https://github.com/vishnubob/wait-for-it
as suggested here: https://docs.docker.com/compose/startup-order/

**Comment by datadarius** [comment]
I have changed the compose file format v2 to enable depends_on.
This is implemented in #40

**Comment by gherkins** [comment]
@ivoba should be fixed then, right?

**Comment by datadarius** [comment]
yep.

**Comment by ivoba** [comment]
yep done :+1:
