### ISSUE TITLE
drop elasticsearch

### ISSUE THREAD

**Issue by gherkins** [nerdpress-org/docker-sf3#55]
i think we should remove elasticsearch from this project
it really has nothing to do with symfonys basic functionality.

And it comlicates the initial setup
> Note: that for Elasticsearch 5 you need to raise max_map_count on the host.
> sudo sysctl -w vm.max_map_count=262144

also when using fosElasticaBundle you'd have to use dev-master with elasticsearch 5.

**Comment by ivoba** [comment]
yes agree
